[package]
name = "type_games"
version = "0.1.0"
authors = ["Thomas Andolf <thomas.andolf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
crossterm = "0.20.0"
